export var MangaStatus;
(function (MangaStatus) {
  MangaStatus['ONGOING'] = 'Ongoing';
  MangaStatus['COMPLETED'] = 'Completed';
})(MangaStatus || (MangaStatus = {}));
export var MangaGenre;
(function (MangaGenre) {
  MangaGenre['ACTION'] = 'Action';
  MangaGenre['ADULT'] = 'Adult';
  MangaGenre['ADVENTURE'] = 'Adventure';
  MangaGenre['COMEDY'] = 'Comedy';
  MangaGenre['COOKING'] = 'Cooking';
  MangaGenre['DOUJINSHI'] = 'Doujinshi';
  MangaGenre['DRAMA'] = 'Drama';
  MangaGenre['ECCHI'] = 'Ecchi';
  MangaGenre['FANTASY'] = 'Fantasy';
  MangaGenre['GENDER_BENDER'] = 'Gender Bender';
  MangaGenre['HAREM'] = 'Harem';
  MangaGenre['HISTORICAL'] = 'Historical';
  MangaGenre['HORROR'] = 'Horror';
  MangaGenre['ISEKAI'] = 'Isekai';
  MangaGenre['JOSEI'] = 'Josei';
  MangaGenre['MANHUA'] = 'Manhua';
  MangaGenre['MANHWA'] = 'Manhwa';
  MangaGenre['MARTIAL_ARTS'] = 'Martial Arts';
  MangaGenre['MATURE'] = 'Mature';
  MangaGenre['MECHA'] = 'Mecha';
  MangaGenre['MEDICAL'] = 'Medical';
  MangaGenre['MYSTERY'] = 'Mystery';
  MangaGenre['ONE_SHOT'] = 'One Shot';
  MangaGenre['PSYCHOLOGICAL'] = 'Psychological';
  MangaGenre['ROMANCE'] = 'Romance';
  MangaGenre['SCHOOL_LIFE'] = 'School Life';
  MangaGenre['SCIFI'] = 'Sci Fi';
  MangaGenre['SEINEN'] = 'Seinen';
  MangaGenre['SHOUJO'] = 'Shoujo';
  MangaGenre['SHOUJO_AI'] = 'Shoujo Ai';
  MangaGenre['SHOUNEN'] = 'Shounen';
  MangaGenre['SHOUNEN_AI'] = 'Shounen Ai';
  MangaGenre['SLICE_OF_LIFE'] = 'Slife of Life';
  MangaGenre['SMUT'] = 'Smut';
  MangaGenre['SPORTS'] = 'Sports';
  MangaGenre['SUPERNATURAL'] = 'Super Natural';
  MangaGenre['TRADEGY'] = 'Tradegy';
  MangaGenre['WEBTOONS'] = 'Webtoons';
  MangaGenre['YAOI'] = 'Yaoi';
  MangaGenre['YURI'] = 'Yuri';
})(MangaGenre || (MangaGenre = {}));

